version: "3.9"
services:
  backend:
    build: backend
    command: >
      sh -c "python manage.py migrate &&
             python manage.py runserver 0.0.0.0:8000"
    volumes:
      - ./backend:/app
    ports:
      - "8000:8000"
  
  db:
    build: docker/postgres
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: password
      POSTGRES_URL: postgres://admin:password@localhost:5432/stak
      POSTGRES_DB: stak
      POSTGRES_HOST: postgres
    ports:
      - "5432:5432"